steps:
  fastq_qc: true
  trimming: true
  alignment: true
  bam_filter: true
  bam_qc: true
  coverage: true
  multiqc: true

alignment:
  tool: bowtie2

coverage:
  tool: deeptools
  rna_strand_mode: none

resources:
  fastqc:
    threads: 1
    mem_mb: 512
    runtime_min: 15
  cutadapt:
    threads: 2
    mem_mb: 1024
    runtime_min: 30
  bowtie2:
    threads: 2
    mem_mb: 2048
    runtime_min: 60
  bowtie2_index:
    threads: 2
    mem_mb: 2048
    runtime_min: 60
  bwa_mem2:
    threads: 2
    mem_mb: 2048
    runtime_min: 60
  bwa_mem2_index:
    threads: 2
    mem_mb: 2048
    runtime_min: 60
  star:
    threads: 2
    mem_mb: 4096
    runtime_min: 90
  star_index:
    threads: 2
    mem_mb: 4096
    runtime_min: 90
  samtools_filter:
    threads: 2
    mem_mb: 1024
    runtime_min: 30
  samtools_qc:
    threads: 1
    mem_mb: 512
    runtime_min: 15
  deeptools:
    threads: 2
    mem_mb: 1024
    runtime_min: 30
  multiqc:
    threads: 1
    mem_mb: 512
    runtime_min: 15
